CREATE TABLE Customer (
  ID INTEGER AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(50) NOT NULL,
  Email VARCHAR(50) NOT NULL,
  Password VARCHAR(50) NOT NULL,
  Address VARCHAR(100) NULL,
  Contact VARCHAR(13) NULL
);

CREATE TABLE Product (
  ID INTEGER AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(50) NOT NULL,
  Description VARCHAR(100) NOT NULL,
  Price INTEGER NOT NULL,
  Rating FLOAT,
  Quantity INTEGER
);

CREATE TABLE Orders (
  ID INTEGER AUTO_INCREMENT PRIMARY KEY,
  ProductId INTEGER NOT NULL,
  FOREIGN KEY(ProductId) REFERENCES Product(ID),
  Status varchar(10),
  CustomerId INTEGER,
  FOREIGN KEY(CustomerId) REFERENCES Customer(ID),
  Date Date ,
  Review INTEGER,
  Quantity INTEGER,
  TotalBill INTEGER
);

CREATE TABLE Cart (
  CustomerId INTEGER NOT NULL,
  ProductId INTEGER NOT NULL,
  Quantity INTEGER DEFAULT 0,
  PRIMARY KEY (CustomerId, ProductId),
  FOREIGN KEY(ProductId) REFERENCES Product(ID),
  FOREIGN KEY(CustomerId) REFERENCES Customer(ID)
);

CREATE TABLE Admin (
  ID INTEGER AUTO_INCREMENT PRIMARY KEY,
  Email VARCHAR(50) NOT NULL,
  Password VARCHAR(50) NOT NULL,
  AccountNumber VARCHAR(20) NOT NULL
);
